language: node_js
node_js: stable
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run www
  - cd www
  - ls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
    target_branch: gh-pages
  